version: "3.9"
services:
  dnstls:
    image: mguletskii/dnstls
    ports:
      - "1853:1853/udp"
    networks:
      host_net:
        ipv4_address: "172.25.192.2"
networks:
  host_net:
    ipam:
      driver: default
      config:
        - subnet: "172.25.192.0/24"